apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tkg-autoscaler.tanzu.vmware.com.0.21.0-dev
  namespace: default
spec:
  refName: tkg-autoscaler.tanzu.vmware.com
  version: 0.21.0-dev
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: # Get this value by pushing to your OCI Registry
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
